Add support for converting docx to pdf using headless libreoffice

diff --git a/share/container/document-to-pixels b/share/container/document-to-pixels
--- a/share/container/document-to-pixels
+++ b/share/container/document-to-pixels
@@ -1,11 +1,33 @@
 #!/bin/bash
 
-IMG_DEPTH=8
+die() {
+    echo "$1" >&2
+    exit 1
+}
+
+# Detect the mime type
+MIME_TYPE=$(file -b --mime-type /tmp/input_file)
+echo "Documet MIME type is $MIME_TYPE"
+echo
+
+# .docx
+if [ $MIME_TYPE = "application/pdf" ]; then
+    ORIGINAL_PDF=/tmp/input_file
+elif [ $MIME_TYPE = "application/vnd.openxmlformats-officedocument.wordprocessingml.document" ]; then
+    echo "Converting document to PDF"
+    CONVERT_MSGS=$(libreoffice --headless --convert-to pdf:writer_pdf_Export --outdir /tmp /tmp/input_file 2>&1)
+    if [ $? -ne 0 ]; then
+        die "Page $PAGE conversion failed: $CONVERT_MSGS"
+    fi
+    ORIGINAL_PDF=/tmp/input_file.pdf
+else
+    die "The document format is not supported"
+fi
 
 echo "Separating document into pages"
+pdfseparate $ORIGINAL_PDF /tmp/page-%d.pdf
 
-pdfseparate /tmp/input_file /tmp/page-%d.pdf
-
+IMG_DEPTH=8
 NUM_PAGES=$(find /tmp/page-*.pdf |wc -l)
 echo "Document has $NUM_PAGES pages"
 echo
